import React, { Component } from "react";
import "flatpickr/dist/themes/material_green.css";
import MultiSelect from "./MultiSelect";
import MultiRouteCode from "./MultiRouteCode";
import MultiVehicleCode from "./MultiVehicleCode";
import { withNamespaces } from "react-i18next";
//import Select1 from './Select';
import SelectionAutoGenerateList from "./SelectionAutoGenerateList";
import Flatpickr from "react-flatpickr";
import { AgGridReact } from "ag-grid-react";
import "ag-grid-community/dist/styles/ag-grid.css";
import "ag-grid-community/dist/styles/ag-theme-balham.css";
import SyncRoundedIcon from "@material-ui/icons/SyncRounded";
import IconButton from "@material-ui/core/IconButton";
import ViewWeekIcon from "@mui/icons-material/ViewWeek";
import LockIcon from "@mui/icons-material/Lock";
import CheckCircleOutlineIcon from "@mui/icons-material/CheckCircleOutline";
import ClearAllIcon from "@mui/icons-material/ClearAll";
// import Tooltip from "@material-ui/core/Tooltip";
import RouteScheduler from "./RouteScheduler";
import Switch from '@mui/material/Switch';
import { getsampleexample } from "../../../service";
import { callWebservice } from "../../../service";
import moment from "moment";
import "../dashboard.scss";
import Select from "react-select";
import {
  Container,
  Row,
  FormGroup,
  Col,
  Form,
  Label,
  Input,
  Media,
  Button,
} from "reactstrap";
import { Box } from "@mui/material";
//import Info from './Info';
import RouteIcon from "@mui/icons-material/Route";
import AltRouteIcon from '@mui/icons-material/AltRoute';
import RefreshIcon from '@mui/icons-material/Refresh';
import HdrAutoIcon from '@mui/icons-material/HdrAuto';
import DoneAllIcon from '@mui/icons-material/DoneAll';
import FiberManualRecordOutlinedIcon from '@mui/icons-material/FiberManualRecordOutlined';
import {
  Toolbar,
  Tooltip,
  styled
} from '@mui/material';
import LockOpenIcon from '@mui/icons-material/LockOpen';
import DeleteIcon from '@mui/icons-material/Delete';

class SideNav_Test extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      addvalidateconfirmShow: false,
      addConfirmShow: false,
      ShowSelectionList: false,
      confirmMessage: "",
      documents: this.props.defaultprocessDocs,
      sameVehicles: this.props.samevehicleChecked,
    };

    this.onTagsChange = this.onTagsChange.bind(this);
  }

  setSelectedSites = (val) => {
    console.log("Thhh setSelectedSites", val);
    this.props.handleSiteChange(val);
  };

  setSelectedRouteCodes = (val) => {
    console.log("selected route codes", val);
    this.props.handleRouteCodeChange(val);
  };

  setSelectedVehicleCodes = (val) => {
    this.props.handleVehicleCodeChange(val);
  };

  selectedSitesArr = (val) => {
    console.log("Thhh selectedSitesArr", val);
    this.props.sitesArr(val);
  };

  selectedRouteCodeArr = (val) => {
    this.props.RouteCodeArr(val);
  };

  selectedVehicleCodeArr = (val) => {
    this.props.VehicleCodeArr(val);
  };

  onTagsChange = (event, value) => {
    //this.props.handleSiteChange(value);
  };
  getRouteScheduler = (routesSchedule) => {
    this.props.getValuestoApp(routesSchedule);
  };

  onDateselection = (date) => {
    console.log("T11 inside dateselection", date);
    const Seldate = moment(date[0]).format("YYYY-MM-DD");
    console.log("T11 inside dateselection", Seldate);
    this.props.handleDateChange(Seldate);
  };

  depalnify = () => {
    this.props.submitDocumentsforTripCreation();
  };

  OnSelectionforAutoGenerateRoute = () => {
    this.setState({
      ShowSelectionList: true,
      //Datalist: this.props.geoData
    });
  };

  autoGeneratedRouteClick = () => {
    this.props.autoGenerateTrips();
  };

  OnSameVehcheckBoxChange = () => {
    console.log("T222 docpanel - to plan change");
    this.setState({ sameVehicles: !this.state.sameVehicles });
    this.props.OncheckedSameVehicles(!this.state.sameVehicles);
  };

  autoResetRoutes = () => {
    this.props.autoResetTrips();
  };

  OnGroupLockingTrips = () => {
    this.props.grouplockTrips();
  };

  OnGroupUnlockingTrips = () => {
    this.props.groupunlockTrips();
  }


  handleCodeChange = (e) => {
    this.props.handleCodeExecution(!this.props.oldCode);
  }

    handleBreaksChange = (e) => {
    this.props.handleBreaksChange(!this.props.breaks);
  }

  OnGroupOptimiseTrips = () => {
    //   this.props.groupOptmiseTrips();

    if (this.props.oldCode) {
      this.props.groupOptmiseTrips();
    }
    else {
      this.props.groupNextBillionsOptmiseTrips();
    }
  };

  OnGroupValidateTrips = () => {
    this.props.onValidateAll();
    /*
          this.setState({
              confirmMessage: this.props.t('AllValidate'),
              addvalidateconfirmShow: true,
          });
*/
  };
  onGroupValidateNo = () => {
    this.setState({
      addvalidateconfirmShow: false,
    });
  };

  onGroupValidateYes = () => {
    this.props.onValidateAll();
    console.log("GV - Yes confirm for group Valdiation");
    this.setState({
      addvalidateconfirmShow: false,
    });
  };

  handleDocProcessChange = (event) => {
    console.log("Changed Value =", event.target.value);
    this.props.onDocProcessChange(event.target.value);
    this.setState({
      documents: event.target.value,
    });
  };

  render() {
    console.log("props of RouteCode", this.props.routecodes);
    let Selection_win_Close = () => this.setState({ ShowSelectionList: false });

    let optionItems = [];
    var optionSelected = {};
    var selectedSite = {};
    let optionRouteCodeItems = [];

    // console.log(optionRouteCodeItems,"route code items")

    var optionSelectedRouteCode = {};
    var selectedRouteCode = {};

    let optionVehicleCodeItems = [];
    var optionSelectedVehicleCode = {};
    var selectedVehicleCode = {};

    var placeHolder = "All";
    this.props.sites &&
      this.props.sites.length > 0 &&
      this.props.sites.map((site) => {
        if (site.id == this.props.selectedSite) {
          selectedSite = site;
          placeHolder = site.value;
          optionSelected.value = site.id;
          optionSelected.label = site.value + "(" + site.id + ")";
        }
        optionItems.push({
          value: site.id,
          label: site.value + "(" + site.id + ")",
        });
      });

    this.props.routecodes &&
      this.props.routecodes.length > 0 &&
      this.props.routecodes.map((routecode) => {
        if (routecode.routeNo == this.props.selectedRouteCode) {
          selectedRouteCode = routecode;
          placeHolder = routecode.routeDesc;
          optionSelected.value = routecode.routeNo;
          optionSelected.label = routecode.routeDesc;
        }
        optionRouteCodeItems.push({
          value: routecode.routeDesc,
          label: routecode.routeDesc,
        });
      });
    this.props.vehicles &&
      this.props.vehicles.length > 0 &&
      this.props.vehicles.map((vehicle) => {
        console.log("Veh details =", vehicle);
        if (vehicle.codeyve == this.props.selectedRouteCode) {
          selectedVehicleCode = vehicle;
          placeHolder = vehicle.routeDesc;
          optionSelected.value = vehicle.codeyve;
          optionSelected.label = vehicle.routeDesc;
        }

        if (vehicle.drivername !== null) {
          optionVehicleCodeItems.push({
            value: vehicle.codeyve,
            label: vehicle.codeyve + " --- " + vehicle.drivername,
          });
        } else {
          optionVehicleCodeItems.push({
            value: vehicle.codeyve,
            label: vehicle.codeyve,
          });
        }
      });

    console.log(this.props.setAutoPopup, "setting open ");
    return (
      <Form className="">
        <Row className="w-100 ">
          <Col md="2">
            <div style={{ display: this.props.vehicleShow }}>
              <FormGroup className="selectNav-container mb-0">
                <MultiSelect
                  setSelectedSites={this.setSelectedSites}
                  selectedSitesArr={this.selectedSitesArr}
                  defaultSelected={this.props.selectedSitesArr}
                  options={optionItems}
                />
              </FormGroup>
            </div>
          </Col>

          <Col md="2">
            <div style={{ display: this.props.vehicleShow }}>
              <FormGroup className="select-Navcontainer mb-0">
                <MultiRouteCode
                  setSelectedRouteCodes={this.setSelectedRouteCodes}
                  selectedRouteCodeArr={this.selectedRouteCodeArr}
                  options={optionRouteCodeItems}
                  updateselectedRCode={this.props.updateselectedRCode}
                  ClearRouteCodes={this.props.ClearRouteCodes}
                  selectedRCode={this.props.selectedRCode}

                />
              </FormGroup>
            </div>
          </Col>
          <Col md="2">
            <div style={{ display: this.props.vehicleShow }}>
              <FormGroup className="select-Navcontainer mb-0">
                <MultiVehicleCode
                  setSelectedVehicleCodes={this.setSelectedVehicleCodes}
                  selectedVehicleCodeArr={this.selectedVehicleCodeArr}
                  options={optionVehicleCodeItems}
                />
              </FormGroup>
            </div>
          </Col>
          <Col md="6">
            <div
              className="SideNav_Btns"
              style={{
                display: this.props.schedulerShow,
                alignSelf: "center",
                justifyContent: "space-between"
              }}
            >
              <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", width: '100%' }}>
                <Toolbar style={{ gap: '16px' }}>
                  <Tooltip
                    title={
                      <span style={{ fontSize: "1.25rem" }}>Refresh</span>}
                  >
                    <IconButton onClick={() => this.props.refreshAllPanels()} style={{ backgroundColor: "#4285F4" }}>
                      <RefreshIcon style={{ fontSize: 25, color: 'white' }} />
                    </IconButton>
                  </Tooltip>
                  <Tooltip
                    title={
                      <span style={{ fontSize: "1.25rem" }}>Generate Route</span>}
                  >
                    <IconButton onClick={this.depalnify} style={{ backgroundColor: "#964B00" }}>
                      <AltRouteIcon style={{ fontSize: 25, color: 'white' }} />
                    </IconButton>
                  </Tooltip>
                  <Tooltip
                    title={
                      <span style={{ fontSize: "1.25rem" }}>Group Optimise</span>}
                  >
                    <IconButton onClick={() => this.OnGroupOptimiseTrips()} style={{ backgroundColor: "#6B7280" }}>
                      <RouteIcon style={{ fontSize: 25, color: 'white' }} />
                    </IconButton>
                  </Tooltip>

                  <Tooltip
                    title={
                      <span style={{ fontSize: "1.25rem" }}>Old Code</span>}
                  >
                    <Switch
                      checked={this.props.oldCode}
                      onChange={this.handleCodeChange}
                      inputProps={{ 'aria-label': 'controlled' }}
                    />
                  </Tooltip>
                </Toolbar>
                <div>
                  {this.props.documentPanel_dateflg && (

                    <Toolbar style={{ gap: '16px' }}>
                      <Tooltip
                        title={
                          <span style={{ fontSize: "1.25rem" }}> Auto Generate Route </span>}
                      >
                        <IconButton onClick={() => this.props.openPopupAuto(true)} style={{ backgroundColor: "#4285F4" }}>
                          <HdrAutoIcon style={{ fontSize: 25, color: 'white' }} />
                        </IconButton>
                      </Tooltip>
                      <Tooltip title={
                        <span style={{ fontSize: "1.25rem" }}> Group Lock </span>}
                      >
                        <IconButton onClick={() => this.OnGroupLockingTrips()} style={{ backgroundColor: "#34D399" }}>
                          <LockIcon style={{ fontSize: 25, color: 'white' }} />
                        </IconButton>
                      </Tooltip>

                      <Tooltip title={
                        <span style={{ fontSize: "1.25rem" }}> Group Unlock </span>}
                      >
                        <IconButton onClick={() => this.OnGroupUnlockingTrips(5)} style={{ backgroundColor: "#8B5CF6" }}>
                          <LockOpenIcon style={{ fontSize: 28, color: 'white' }} />
                        </IconButton>
                      </Tooltip>

                      <Tooltip title={
                        <span style={{ fontSize: "1.25rem" }}> Group Validate </span>}
                      >
                        <IconButton onClick={() => this.OnGroupValidateTrips()} style={{ backgroundColor: "#F59E0B" }}>
                          <DoneAllIcon style={{ fontSize: 25, color: 'white' }} />
                        </IconButton>
                      </Tooltip>
                      <Tooltip title={
                        <span style={{ fontSize: "1.25rem" }}> Group Delete Trips </span>}
                      >
                        <IconButton onClick={() => this.autoResetRoutes()} style={{ backgroundColor: "#EF4444    " }}>
                          <DeleteIcon style={{ fontSize: 25, color: 'white' }} />
                        </IconButton>
                      </Tooltip>

                      <Tooltip
                        title={
                          <span style={{ fontSize: "1.25rem" }}>Breaks</span>}
                      >
                        <Switch
                          checked={this.props.breaks}
                          onChange={this.handleBreaksChange}
                          inputProps={{ 'aria-label': 'controlled' }}
                        />
                      </Tooltip>
                    </Toolbar>
                  )}
                </div>
              </div>
            </div>


          </Col>
          <div
            style={{
              display: this.props.vrShow,
              width: "60%",
              alignSelf: "center",
            }}
          >
            <button
              type="button"
              class="btn btn-primary"
              style={{ display: this.props.vrShow, marginLeft: "1000px" }}
              onClick={() => { this.props.onVRhide() }}
            >
              <span>{this.props.t("Back")}</span>
            </button>
          </div>

          <SelectionAutoGenerateList
            show={this.state.ShowSelectionList}
            onHide={Selection_win_Close}
            Vehiclelist={this.props.vehiclePanel}
          ></SelectionAutoGenerateList>
        </Row>
      </Form>
    );
  }
}

export default withNamespaces()(SideNav_Test);
