import React, { Component } from "react";
import Select from "react-select";
import Alert from "../Panel/Alert";
import "flatpickr/dist/themes/material_green.css";
import MultiSelect from "./MultiSelect";
import MultiRouteCode from "./MultiRouteCode";
import { withNamespaces } from "react-i18next";
import Flatpickr from "react-flatpickr";
import { AgGridReact } from "ag-grid-react";
import "ag-grid-community/dist/styles/ag-grid.css";
import "ag-grid-community/dist/styles/ag-theme-balham.css";
import SyncRoundedIcon from "@material-ui/icons/SyncRounded";
import IconButton from "@material-ui/core/IconButton";
import Tooltip from "@material-ui/core/Tooltip";
import RouteScheduler from "./RouteScheduler";
import "../dashboard.scss";
import moment from "moment";
import AlertNew from "../Panel/AlertNew";
import { Container, Row, FormGroup, Input, Form } from "reactstrap";
//import Info from './Info';

class SideNav extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      addvalidateconfirmShow: false,
      addConfirmShow: false,
      addAlertShow: false,
      errorMessage: "",
      msgtype: "",
      type : "",
      ShowSelectionList: false,
      confirmMessage: "",
      documents: this.props.defaultprocessDocs,
      sameVehicles: this.props.samevehicleChecked,
    };
    this.onTagsChange = this.onTagsChange.bind(this);
  }

  setSelectedRouteCodes = (val) => {
    this.props.handleRouteCodeChange(val);
  };

  selectedRouteCodeArr = (val) => {
    this.props.RouteCodeArr(val);
  };

  setSelectedSites = (val) => {
    this.props.handleSiteChange(val);
  };

  selectedSitesArr = (val) => {
    this.props.sitesArr(val);
  };

  onTagsChange = (event, value) => {
    //this.props.handleSiteChange(value);
  };
  getRouteScheduler = (routesSchedule) => {
    this.props.getValuestoApp(routesSchedule);
  };

  onDateselection = (date) => {
    const Seldate = moment(date[0]).format("YYYY-MM-DD");
    this.props.handleDateChange(Seldate);
  };

  // Auto

  autoGeneratedRouteClick = () => {
    this.props.autoGenerateTrips();
    this.setState({
      addConfirmShow: false,
      msgtype: "",
      type:"",
    });
  };

  OnSameVehcheckBoxChange = () => {
    this.setState({ sameVehicles: !this.state.sameVehicles });
    this.props.OncheckedSameVehicles(!this.state.sameVehicles);
  };

  autoResetRoutes = () => {
    this.props.autoResetTrips();
  };

  OnGroupLockingTrips = () => {
    this.props.grouplockTrips();
  };

  onConfirmNo = () => {
    this.setState({
      addConfirmShow: false,
      msgtype: "",
      type : "",
    });
  };

  onConfirmClick = (type) => {
    let tripsList = this.props.tripsPanel;

    var Validatecount = 0;
    var Lockcount = 0;
    var OptimisedTrips = 0;
    var DeletedCount = 0;
    var DocCount = 0;
    var unlockcount = 0;
    for (let jj = 0; jj < this.props.dropsPanel.drops.length; jj++) {
      let doc = this.props.dropsPanel.drops[jj];
      if (
        (doc.type === "open" || doc.type === "Allocated") &&
        (doc.dlvystatus === "0" || doc.dlvystatus === "8")
      ) {
        DocCount = DocCount + 1;
      }
    }

    for (let jk = 0; jk < this.props.dropsPanel.pickUps.length; jk++) {
      let doc = this.props.dropsPanel.pickUps[jk];
      if (
        doc.type === "open" &&
        (doc.dlvystatus === "0" || doc.dlvystatus === "8")
      ) {
        DocCount = DocCount + 1;
      }
    }

    for (let i = 0; i < tripsList.length; i++) {
      var trip = tripsList[i];
      if (trip.lock && !trip.tmsValidated) {
        Validatecount = Validatecount + 1;
      }
      if (!trip.lock && trip.optistatus === "Optimized") {
        Lockcount = Lockcount + 1;
      }
      if (!trip.lock && trip.optistatus === "Open") {
        OptimisedTrips = OptimisedTrips + 1;
      }
      if (
        !trip.lock &&
        (trip.optistatus === "Optimized" || trip.optistatus === "Open")
      ) {
        DeletedCount = DeletedCount + 1;
      }
    }

    let mess = "";
    if (type === "1") {
      if (DocCount > 0) {
//        mess = "Are you sure you want to confirm the auto-generation of the trips?";
//        this.setState({
//           addConfirmShow : true,
//          confirmMessage: mess,
//          msgtype: type,
//          type : "success"
//        });
         this.props.openPopupAuto(true);
      } else {
        this.setState({
          confirmMessage: "No documents are available for trip creation.",
          addConfirmShow: true,
          type : "error",
          msgtype: type,
        });
      }
    } else if (type === "2") {
      if (Lockcount > 0) {
        mess = "Are you sure you want to lock all the optimised trips?";
        this.setState({
          addConfirmShow: true,
          confirmMessage: mess,
          msgtype: type,
           type : "success"
        });
      } else {
        this.setState({
          confirmMessage : "No trips are available for Locking.",
          addConfirmShow: true,
          type : "error",
           msgtype: type
        });
      }
    } else if (type === "3") {
      if (Validatecount > 0) {
        mess = "Are you sure you want to validate all the non-validated trips?";
        this.setState({
          addConfirmShow : true,
          confirmMessage: mess,
          msgtype: type,
           type : "success"
        });
      } else {
        this.setState({
          confirmMessage: "No trips are available for validation.",
          addConfirmShow: true,
           msgtype: type,
          type : "error",

        });
      }
    } else if (type === "4") {
      if (DeletedCount > 0) {
        mess = "Are you sure you want to delete all the optimised trips?";
        this.setState({
          addConfirmShow: true,
          confirmMessage: mess,
          msgtype: type,
           type : "success"
        });
      } else {
        this.setState({
          confirmMessage: "No trips are available for deletion.",
          addConfirmShow: true,
           msgtype: type,
          type : "error"
        });
      }
    } else if (type === "5") {
      if (OptimisedTrips > 0) {
        mess = "Are you sure you want to optimize the trips?";
        this.setState({
          addConfirmShow: true,
          confirmMessage: mess,
          msgtype: type,
           type : "success"
        });
      } else {
        this.setState({
          confirmMessage: "No open trips are available for optimization.",
          addConfirmShow: true,
           msgtype: type,
          type : "error"
        });
      }
    }
    else if (type === "6") {
          if (Validatecount > 0) {
            mess = "Are you sure you want to unlock all the locked trips?";
            this.setState({
              addConfirmShow : true,
              confirmMessage: mess,
              msgtype: type,
               type : "success"
            });
          } else {
            this.setState({
              confirmMessage: "No trips are available for unlock.",
              addConfirmShow: true,
               msgtype: type,
              type : "error",

            });
          }
          }
  };

  onConfirmYes = (type) => {
    if (type === "1") {
      // this.autoGeneratedRouteClick();
      this.props.openPopupAuto(true);
    } else if (type === "2") {
      this.OnGroupLockingTrips();
    } else if (type === "3") {
      this.OnGroupValidateTrips();
    } else if (type === "4") {
      this.autoResetRoutes();
    } else if (type === "5") {
      this.OnGroupOptimiseTrips();
    }
    else if (type === "6") {
          this.OnGroupUnlockTrips();
   }


    //   this.props.confirmTrip(this.state.currentTrip, 'Open');
    this.setState({
      addConfirmShow: false,
      confirmMessage : "",
      msgtype: "",
      type : "",
    });
  };

  OnGroupOptimiseTrips = () => {
    this.props.groupOptmiseTrips();
  };

   OnGroupUnlockTrips = () => {
      this.props.groupunlockTrips();
    };


  OnGroupValidateTrips = () => {
    this.props.onValidateAll();
    /*
          this.setState({
              confirmMessage: this.props.t('AllValidate'),
              addvalidateconfirmShow: true,
          });
*/
  };
  onGroupValidateNo = () => {
    this.setState({
      addvalidateconfirmShow: false,
    });
  };

  onGroupValidateYes = () => {
    this.props.onValidateAll();
    this.setState({
      addvalidateconfirmShow: false,
    });
  };

  // handleDocProcessChange = (event) => {
  //   this.props.onDocProcessChange(event.target.value);
  //   this.setState({
  //     documents: event.target.value,
  //   });
  // };

  handleDocProcessChange = (event) => {
    const value = event.target.value;

    // Allow only numeric values and restrict special characters
    if (/^\d*$/.test(value)) {
      // Check if the input contains only digits
      const numericValue = parseInt(value, 10);

      if (numericValue > 0) {
        // If value is greater than 0, update state and call the parent handler
        this.props.onDocProcessChange(numericValue);
        this.setState({
          documents: numericValue,
        });
      } else if (value === "") {
        // Allow clearing the input
        this.setState({
          documents: "",
        });
      }
    }
  };

  render() {
    let optionItems = [];
    var optionSelected = {};
    var selectedSite = {};
    let addAlertClose = () => this.setState({ addConfirmShow: false });
    let optionRouteCodeItems = [];
    var optionSelectedRouteCode = {};
    var selectedRouteCode = {};
    var placeHolder = "All";
    this.props.sites &&
      this.props.sites.length > 0 &&
      this.props.sites.map((site) => {
        if (site.id == this.props.selectedSite) {
          selectedSite = site;
          placeHolder = site.value;
          optionSelected.value = site.id;
          optionSelected.label = site.value + "(" + site.id + ")";
        }
        optionItems.push({
          value: site.id,
          label: site.value + "(" + site.id + ")",
        });
      });
    this.props.routecodes &&
      this.props.routecodes.length > 0 &&
      this.props.routecodes.map((routecode) => {
        if (routecode.routeNo == this.props.selectedRouteCode) {
          selectedRouteCode = routecode;
          placeHolder = routecode.routeDesc;
          optionSelected.value = routecode.routeNo;
          optionSelected.label = routecode.routeDesc;
        }
        optionRouteCodeItems.push({
          value: routecode.routeNo,
          label: routecode.routeDesc,
        });
      });

    return (
      <>
        <Form className="row_nav" style={{ height: "100%" }}>
          <div style={{ display: this.props.vehicleShow }}>
            <FormGroup className="select2-container mb-0 col-md-2 col-lg-2 col-xl-2">
              <MultiSelect
                setSelectedSites={this.setSelectedSites}
                selectedSitesArr={this.selectedSitesArr}
                options={optionItems}
              />
            </FormGroup>
          </div>
          <div style={{ display: this.props.vehicleShow }}>
            <FormGroup className="Select2-date p-1 ml-1 col-md-2 col-lg-2 col-xl-2 mb-1">
              <span style={{color:"#505D69",fontWeight:"bold"}}>Date </span>

              <Flatpickr

                className="form-control"
                dateFormat="m/d/Y"
                style={{ width: "auto",fontWeight:"bold" }}
                value={this.props.selectedDate}
                onChange={this.onDateselection}
              />
            </FormGroup>
            &emsp;
          </div>
          <div style={{ display: this.props.vehicleShow }}>
            <div
              className="refreshbtn"
              style={{ paddingTop: "25px", paddingLeft: "25px" }}
            >
              <Tooltip title="Refresh">
                <SyncRoundedIcon
                  color="primary"
                  style={{ fontSize: "28" }}
                  onClick={() => this.props.refreshAllPanels()}
                />
              </Tooltip>
            </div>
          </div>
          <div style={{ display: this.props.vehicleShow }}>
            <FormGroup className="select2-container ml-3 mb-0 col-md-2 col-lg-2 col-xl-2">
              <MultiRouteCode
                setSelectedRouteCodes={this.setSelectedRouteCodes}
                selectedRouteCodeArr={this.selectedRouteCodeArr}
                options={optionRouteCodeItems}
              />
            </FormGroup>
          </div>

          <div
            className="SideNav_Btns"
            style={{
              alignSelf: "center",
              justifyContent: "space-between",
              display: this.props.vehicleShow,
            }}
          >

            <button
              type="button"
              class="btn btn-info "
              onClick={() => this.onConfirmClick("1")}
            >
              Auto-Generate Trips
            </button>

            <button
              type="button"
              class="btn btn-dark"
              onClick={() => this.onConfirmClick("5")}
            >
              Group Optimise
            </button>
            <button
              type="button"
              class="btn btn-success"
              onClick={() => this.onConfirmClick("2")}
            >
              Group Lock
            </button>

             <button
                          type="button"
                          class="btn btn-info"
                          onClick={() => this.onConfirmClick("6")}
                        >
                          Group Unlock
                        </button>

            <button
              type="button"
              class="btn btn-primary"
              onClick={() => this.onConfirmClick("3")}
            >
              Group Validate
            </button>

            <button
              type="button"
              class="btn btn-dark "
              onClick={() => this.onConfirmClick("4")}
            >
            Group Delete Trips
            </button>

            <>
              {" "}
              <span style={{ fontSize: "16px", fontWeight: "bold" }}>
                Max Stops :{" "}
              </span>{" "}
              <input
                style={{
                  width: 50,
                  height: "40px",
                  fontSize: "16px",
                  fontWeight: "bolder",
                  textAlign: "center",
                }}
                type="text"
                onChange={this.handleDocProcessChange}
                value={this.state.documents}
              />{" "}
            </>
          </div>
          <div
            style={{
              display: this.props.vrShow,
              width: "60%",
              alignSelf: "center",
            }}
          >
            <ul className="list-unstyled CTAs" style={{ float: "center" }}>
              <li>
                <button
                  type="button"
                  class="btn btn-primary"
                  style={{ display: this.props.vrShow }}
                  onClick={() => this.props.onVRhide()}
                >
                  <span>{this.props.t("Back")}</span>
                </button>
              </li>
            </ul>
          </div>
        </Form>
        <AlertNew
          show={this.state.addConfirmShow}
          onClose={this.onConfirmNo}
          message={this.state.confirmMessage}
          onConfirm={this.onConfirmYes}
          msgtype={this.state.msgtype}
          type = {this.state.type}
        ></AlertNew>
      </>
    );
  }
}

export default withNamespaces()(SideNav);
