import React, { Component } from "react";
import Select from "react-select";
import Alert from "../Panel/Alert";
import "flatpickr/dist/themes/material_green.css";
import MultiSelect from "./MultiSelect";
import MultiRouteCode from "./MultiRouteCode";
import { withNamespaces } from "react-i18next";
import Flatpickr from "react-flatpickr";
import { AgGridReact } from "ag-grid-react";
import "ag-grid-community/dist/styles/ag-grid.css";
import "ag-grid-community/dist/styles/ag-theme-balham.css";
import SyncRoundedIcon from "@material-ui/icons/SyncRounded";
import IconButton from "@material-ui/core/IconButton";
import DeleteIcon from '@mui/icons-material/Delete';
import HdrAutoIcon from '@mui/icons-material/HdrAuto';
import DoneAllIcon from '@mui/icons-material/DoneAll';
import RouteScheduler from "./RouteScheduler";
import SyncAltIcon from '@material-ui/icons/SyncAlt';
import "../dashboard.scss";
import moment from "moment";
import AlertNew from "../Panel/AlertNew";
import { Container, Row, FormGroup, Input, Form } from "reactstrap";
import Box from '@mui/material/Box';
//import Info from './Info';
import {
  Toolbar,
  Tooltip,
  styled
} from '@mui/material';
import RouteIcon from '@mui/icons-material/Route';
import LockIcon from '@mui/icons-material/Lock';
import LockOpenIcon from '@mui/icons-material/LockOpen';
import { ToastContainer, toast } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import GroupDeleteModal from "../Panel/GroupDeleteModal";


const StyledIconButton = styled(IconButton)(({ theme, bgcolor }) => ({
  backgroundColor: bgcolor || theme.palette.primary.main,
  '&:hover': {
    backgroundColor: theme.palette.action.hover,
  },
  padding: theme.spacing(1),
  margin: theme.spacing(0, 0.5),
  borderRadius: theme.shape.borderRadius,
}));



class SideNav extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      addvalidateconfirmShow: false,
      addConfirmShow: false,
      addAlertShow: false,
      errorMessage: "",
      msgtype: "",
      type: "",
      ShowSelectionList: false,
      confirmMessage: "",
      documents: this.props.defaultprocessDocs,
      sameVehicles: this.props.samevehicleChecked,
      groupDeleteModalOpen: false,
    };
    this.onTagsChange = this.onTagsChange.bind(this);
  }

  setSelectedRouteCodes = (val) => {
    this.props.handleRouteCodeChange(val);
  };

  selectedRouteCodeArr = (val) => {
    this.props.RouteCodeArr(val);
  };

  setSelectedSites = (val) => {
    this.props.handleSiteChange(val);
  };

  selectedSitesArr = (val) => {
    this.props.sitesArr(val);
  };

  onTagsChange = (event, value) => {
    //this.props.handleSiteChange(value);
  };
  getRouteScheduler = (routesSchedule) => {
    this.props.getValuestoApp(routesSchedule);
  };

  onDateselection = (date) => {
    const Seldate = moment(date[0]).format("YYYY-MM-DD");
    this.props.handleDateChange(Seldate);
  };

  // Auto

  autoGeneratedRouteClick = () => {
    this.props.autoGenerateTrips();
    this.setState({
      addConfirmShow: false,
      msgtype: "",
      type: "",
    });
  };

  OnSameVehcheckBoxChange = () => {
    this.setState({ sameVehicles: !this.state.sameVehicles });
    this.props.OncheckedSameVehicles(!this.state.sameVehicles);
  };

  autoResetRoutes = () => {
    this.props.autoResetTrips();
  };

  OnGroupLockingTrips = () => {
    this.props.grouplockTrips();
  };

  handleGroupDelete = (selectedTripIds) => {
  // Pass up to parent — adjust prop name to match your app
  this.props.autoResetTrips(selectedTripIds);
};

  onConfirmNo = () => {
    this.setState({
      addConfirmShow: false,
      msgtype: "",
      type: "",
    });
  };

  notifyError = (message) => toast.error(message, { autoClose: 3000, style: { zIndex: 1050 } })

  onConfirmClick = (type) => {
    let tripsList = this.props.tripsPanel;

    var noDriverTrips = "";
    var nonDeliverableDocsAtValidation = "";
    var Validatecount = 0;
    var Lockcount = 0;
    var OptimisedTrips = 0;
    var DeletedCount = 0;
    var DocCount = 0;
    for (let jj = 0; jj < this.props.dropsPanel.drops.length; jj++) {
      let doc = this.props.dropsPanel.drops[jj];
      if (
        (doc.type === "open" || doc.type === "Allocated") &&
        (doc.dlvystatus === "0" || doc.dlvystatus === "8")
      ) {
        DocCount = DocCount + 1;
      }
    }

    for (let jk = 0; jk < this.props.dropsPanel.pickUps.length; jk++) {
      let doc = this.props.dropsPanel.pickUps[jk];
      if (
        doc.type === "open" &&
        (doc.dlvystatus === "0" || doc.dlvystatus === "8")
      ) {
        DocCount = DocCount + 1;
      }
    }

    for (let i = 0; i < tripsList.length; i++) {
      var trip = tripsList[i];
      if (trip.driverId === "") {
        noDriverTrips += trip.itemCode + '\n';
      }
      if (trip.lock && !trip.tmsValidated) {
        // let nonDeliverableCount = 0;
        // for (let ll = 0; ll < trip.docDetails?.length; ll++) {
        //   let  doc = trip.docDetails[ll];
        //   if (doc.documentStatus !== "Deliverable") {
        //     nonDeliverableCount = nonDeliverableCount + 1;
        //     nonDeliverableDocsAtValidation += doc.documentNo + '\n';
        //   }
        // }
        // if (nonDeliverableCount === 0) { 
        Validatecount = Validatecount + 1;
        // }
      }
      if (!trip.lock && trip.optistatus === "Optimized" && trip.driverId !== "") {
        Lockcount = Lockcount + 1;
      }
      if (!trip.lock && trip.optistatus === "Open") {
        OptimisedTrips = OptimisedTrips + 1;
      }
      if (
        !trip.lock &&
        (trip.optistatus === "Optimized" || trip.optistatus === "Open")
      ) {
        DeletedCount = DeletedCount + 1;
      }
    }

    let mess = "";
    if (type === "1") {
      if (DocCount > 0) {
        //        mess = "Are you sure you want to confirm the auto-generation of the trips?";
        //        this.setState({
        //          addConfirmShow : true,
        //          confirmMessage: mess,
        //          msgtype: type,
        //          type : "success"
        //        });
        this.props.openPopupAuto(true);
      } else {
        this.setState({
          confirmMessage: "There are no documents available for trip creation.",
          addConfirmShow: true,
          type: "error",
          msgtype: type,
        });
      }
    } else if (type === "2") {
          if (this.props.isTripModified) {
      this.notifyError('Please confirm the modified trip prior to group locking trips in order to save the changes.')
      return;
    }
      if (noDriverTrips !== "") {
        mess = `The following trips don't have driver, Please assign driver before locking.  \n  ${noDriverTrips}`;
        this.setState({
          addConfirmShow: true,
          confirmMessage: mess,
          msgtype: type,
          type: "error"
        });
      }
      else if (Lockcount > 0) {
        mess = "Are you sure you want to lock the trip(s)?";
        this.setState({
          addConfirmShow: true,
          confirmMessage: mess,
          msgtype: type,
          type: "success"
        });
      } else {
        this.setState({
          confirmMessage: "There are no unlocked trips.",
          addConfirmShow: true,
          type: "error",
          msgtype: type
        });
      }
    } else if (type === "3") {
      // if (nonDeliverableDocsAtValidation !== "") {
      //   this.setState({
      //     confirmMessage: `The following documents in the trips are no in Deliverable status. \n ${nonDeliverableDocsAtValidation}`,
      //     addConfirmShow: true,
      //     msgtype: type,
      //     type: "error",
      //   });
      // }
      if (Validatecount > 0) {
        mess = "Are you sure you want to validate the trip(s)?";
        this.setState({
          addConfirmShow: true,
          confirmMessage: mess,
          msgtype: type,
          type: "success"
        });
      } else {
        this.setState({
          confirmMessage: "There are no trips available to validate.",
          addConfirmShow: true,
          msgtype: type,
          type: "error",

        });
      }
    } else if (type === "4") {
      // if (DeletedCount > 0) {
      //   mess = "Are you sure you want to delete all the unlocked trip(s)?";
      //   this.setState({
      //     addConfirmShow: true,
      //     confirmMessage: mess,
      //     msgtype: type,
      //     type: "success"
      //   });
      // } else {
      //   this.setState({
      //     confirmMessage: "There are no trips available to delete.",
      //     addConfirmShow: true,
      //     msgtype: type,
      //     type: "error"
      //   });
      // }
      this.setState({ groupDeleteModalOpen: true });
    } else if (type === "5") {
      if (OptimisedTrips > 0) {
        mess = "Are you sure you want to optimize the trip(s)?";
        this.setState({
          addConfirmShow: true,
          confirmMessage: mess,
          msgtype: type,
          type: "success"
        });
      } else {
        this.setState({
          confirmMessage: "There are no trips available to optimize.",
          addConfirmShow: true,
          msgtype: type,
          type: "error"
        });
      }
    }
    else if (type === "6") {
      if (Validatecount > 0) {
        mess = "Are you sure you want to unlock the trip(s)?";
        this.setState({
          addConfirmShow: true,
          confirmMessage: mess,
          msgtype: type,
          type: "success"
        });
      } else {
        this.setState({
          confirmMessage: "There are no locked trips.",
          addConfirmShow: true,
          msgtype: type,
          type: "error"
        });
      }
    }
  };

  onConfirmYes = (type) => {
    if (type === "1") {
      // this.autoGeneratedRouteClick();
      this.props.openPopupAuto(true);
    } else if (type === "2") {
      this.OnGroupLockingTrips();
    } else if (type === "3") {
      this.OnGroupValidateTrips();
    } else if (type === "4") {
      this.autoResetRoutes();
    } else if (type === "5") {
      this.OnGroupOptimiseTrips();
    }
    else if (type === "6") {
      this.OnGroupUnlockTrips();
    }


    //   this.props.confirmTrip(this.state.currentTrip, 'Open');
    this.setState({
      addConfirmShow: false,
      confirmMessage: "",
      msgtype: "",
      type: "",
    });
  };

  OnGroupOptimiseTrips = () => {
    //  this.props.groupOptmiseTrips();


    this.props.groupNextBillionsOptmiseTrips();
  };


  OnGroupUnlockTrips = () => {
    this.props.groupunlockTrips();
  };

  OnGroupValidateTrips = () => {
    this.props.onValidateAll();
    /*
          this.setState({
              confirmMessage: this.props.t('AllValidate'),
              addvalidateconfirmShow: true,
          });
*/
  };
  onGroupValidateNo = () => {
    this.setState({
      addvalidateconfirmShow: false,
    });
  };

  onGroupValidateYes = () => {
    this.props.onValidateAll();
    this.setState({
      addvalidateconfirmShow: false,
    });
  };

  // handleDocProcessChange = (event) => {
  //   this.props.onDocProcessChange(event.target.value);
  //   this.setState({
  //     documents: event.target.value,
  //   });
  // };

  handleDocProcessChange = (event) => {
    const value = event.target.value;

    // Allow only numeric values and restrict special characters
    if (/^\d*$/.test(value)) {
      // Check if the input contains only digits
      const numericValue = parseInt(value, 10);

      if (numericValue > 0) {
        // If value is greater than 0, update state and call the parent handler
        this.props.onDocProcessChange(numericValue);
        this.setState({
          documents: numericValue,
        });
      } else if (value === "") {
        // Allow clearing the input
        this.setState({
          documents: "",
        });
      }
    }
  };

  render() {
    let optionItems = [];
    var optionSelected = {};
    var selectedSite = {};
    let addAlertClose = () => this.setState({ addConfirmShow: false });
    let optionRouteCodeItems = [];
    var optionSelectedRouteCode = {};
    var selectedRouteCode = {};
    var placeHolder = "All";
    this.props.sites &&
      this.props.sites.length > 0 &&
      this.props.sites.map((site) => {
        if (site.id == this.props.selectedSite) {
          selectedSite = site;
          placeHolder = site.value;
          optionSelected.value = site.id;
          optionSelected.label = site.value + "(" + site.id + ")";
        }
        optionItems.push({
          value: site.id,
          label: site.value + "(" + site.id + ")",
        });
      });
    this.props.routecodes &&
      this.props.routecodes.length > 0 &&
      this.props.routecodes.map((routecode) => {
        if (routecode.routeNo == this.props.selectedRouteCode) {
          selectedRouteCode = routecode;
          placeHolder = routecode.routeDesc;
          optionSelected.value = routecode.routeNo;
          optionSelected.label = routecode.routeDesc;
        }
        optionRouteCodeItems.push({
          value: routecode.routeNo,
          label: routecode.routeDesc,
        });
      });




    return (
      <>
        <Form className="row_nav" style={{ height: "100%" }}>
          <div style={{ display: this.props.vehicleShow }}>
            <FormGroup className="select2-container mb-0 col-md-2 col-lg-2 col-xl-2">
              <MultiSelect
                setSelectedSites={this.setSelectedSites}
                selectedSitesArr={this.selectedSitesArr}
                options={optionItems}
              />
            </FormGroup>
          </div>
          <div style={{ display: this.props.vehicleShow }}>
            <FormGroup className="Select2-date p-1 ml-1 col-md-2 col-lg-2 col-xl-2 mb-1">
              <span style={{ color: "#505D69", fontWeight: "bold" }}>Date </span>

              <Flatpickr

                className="form-control"
                dateFormat="m/d/Y"
                style={{ width: "auto", fontWeight: "bold" }}
                value={this.props.selectedDate}
                onChange={this.onDateselection}
              />
            </FormGroup>
            &emsp;
          </div>

          <div style={{ display: this.props.vehicleShow }}>
            <FormGroup className="select2-container ml-3 mb-0 col-md-2 col-lg-2 col-xl-2">
              <MultiRouteCode
                setSelectedRouteCodes={this.setSelectedRouteCodes}
                selectedRouteCodeArr={this.selectedRouteCodeArr}
                options={optionRouteCodeItems}
              />
            </FormGroup>
          </div>

          <div
            //  className="SideNav_Btns"
            style={{
              alignSelf: "center",
              // display : 'flex',

              justifyContent: "space-between",
              display: this.props.vehicleShow,
            }}
          >
            <Toolbar style={{ gap: '16px' }}>
              <Tooltip
                title={
                  <span style={{ fontSize: "1.25rem" /* 20px */ }}> Auto Generate Route </span>}
              >
                <IconButton style={{ backgroundColor: "#4285F4" }}>
                  <HdrAutoIcon style={{ fontSize: 28, color: 'white' }} onClick={() => this.onConfirmClick("1")} />
                </IconButton>
              </Tooltip>

              <Tooltip title={
                <span style={{ fontSize: "1.25rem" /* 20px */ }}> Group Optimise </span>}
              >
                <IconButton style={{ backgroundColor: "#6B7280" }}>
                  <RouteIcon style={{ fontSize: 28, color: 'white' }} onClick={() => this.onConfirmClick("5")} />
                </IconButton>
              </Tooltip>

              <Tooltip title={
                <span style={{ fontSize: "1.25rem" /* 20px */ }}> Group Lock </span>}
              >
                <IconButton style={{ backgroundColor: "#34D399" }}>
                  <LockIcon style={{ fontSize: 28, color: 'white' }} onClick={() => this.onConfirmClick("2")} />
                </IconButton>
              </Tooltip>

              <Tooltip title={
                <span style={{ fontSize: "1.25rem" /* 20px */ }}> Group Unlock </span>}
              >
                <IconButton style={{ backgroundColor: "#8B5CF6" }}>
                  <LockOpenIcon style={{ fontSize: 28, color: 'white' }} onClick={() => this.onConfirmClick("6")} />
                </IconButton>
              </Tooltip>

              <Tooltip title={
                <span style={{ fontSize: "1.25rem" /* 20px */ }}> Group Validate </span>}
              >
                <IconButton style={{ backgroundColor: "#F59E0B" }}>
                  <DoneAllIcon style={{ fontSize: 28, color: 'white' }} onClick={() => this.onConfirmClick("3")} />
                </IconButton>
              </Tooltip>

              <Tooltip title={
                <span style={{ fontSize: "1.25rem" /* 20px */ }}> Group Delete Trips </span>}
              >
                <IconButton style={{ backgroundColor: "#EF4444    " }}>
                  <DeleteIcon style={{ fontSize: 28, color: 'white' }} onClick={() => this.onConfirmClick("4")} />
                </IconButton>
              </Tooltip>
            </Toolbar>

          </div>

          <div style={{ display: this.props.vehicleShow, alignSelf: "center", }}>
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: "16px",
                marginLeft: "12px",
                alignSelf: "center",
              }}
            >

              <Tooltip title={<span style={{ fontSize: "1.1rem" }}>Sync Data</span>}>
                <IconButton
                  style={{
                    display: this.props.vehicleShow,
                    backgroundColor: "#0EA5E9",
                  }}
                  onClick={this.props.handleSyncTrips}
                >
                  <SyncAltIcon style={{ fontSize: 26, color: "white" }} />
                </IconButton>
              </Tooltip>


              <button
                type="button"
                class="btn btn-primary"
                onClick={() => this.props.refreshAllPanels()}
              >
                Refresh
              </button>
            </div>
          </div>
          <div
            style={{
              display: this.props.vrShow,
              width: "60%",
              alignSelf: "center",
            }}
          >
            <ul className="list-unstyled CTAs" style={{ float: "center" }}>
              <li>
                <button
                  type="button"
                  class="btn btn-primary"
                  style={{ display: this.props.vrShow }}
                  onClick={() => this.props.onVRhide()}
                >
                  <span>{this.props.t("Back")}</span>
                </button>
              </li>
            </ul>
          </div>
        </Form>
        <GroupDeleteModal
  open={this.state.groupDeleteModalOpen}
  onClose={() => this.setState({ groupDeleteModalOpen: false })}
  tripsPanel={this.props.tripsPanel}
  onConfirmDelete={this.handleGroupDelete}
/>
        <AlertNew
          show={this.state.addConfirmShow}
          onClose={this.onConfirmNo}
          message={this.state.confirmMessage}
          onConfirm={this.onConfirmYes}
          msgtype={this.state.msgtype}
          type={this.state.type}
        ></AlertNew>
      </>
    );
  }
}

export default withNamespaces()(SideNav);
