import React, { Component } from "react";
import Select from "react-select";
import Alert from "../Panel/Alert";
import "flatpickr/dist/themes/material_green.css";
import MultiSelect from "./MultiSelect";
import MultiRouteCode from "./MultiRouteCode";
import { withNamespaces } from "react-i18next";
import Flatpickr from "react-flatpickr";
import { AgGridReact } from "ag-grid-react";
import "ag-grid-community/dist/styles/ag-grid.css";
import "ag-grid-community/dist/styles/ag-theme-balham.css";
import SyncRoundedIcon from "@material-ui/icons/SyncRounded";
import IconButton from "@material-ui/core/IconButton";
import DeleteIcon from '@mui/icons-material/Delete';
import HdrAutoIcon from '@mui/icons-material/HdrAuto';
import DoneAllIcon from '@mui/icons-material/DoneAll';
import RouteScheduler from "./RouteScheduler";
import "../dashboard.scss";
import moment from "moment";
import Switch from '@mui/material/Switch';
import AlertNew from "../Panel/AlertNew";
import { Container, Row, FormGroup, Input, Form } from "reactstrap";
import Box from '@mui/material/Box';
//import Info from './Info';
import {
  Toolbar,
  Tooltip,
  styled
} from '@mui/material';
import RouteIcon from '@mui/icons-material/Route';
import LockIcon from '@mui/icons-material/Lock';
import LockOpenIcon from '@mui/icons-material/LockOpen';

const StyledIconButton = styled(IconButton)(({ theme, bgcolor }) => ({
  backgroundColor: bgcolor || theme.palette.primary.main,
  '&:hover': {
    backgroundColor: theme.palette.action.hover,
  },
  padding: theme.spacing(1),
  margin: theme.spacing(0, 0.5),
  borderRadius: theme.shape.borderRadius,
}));



class SideNav extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      addvalidateconfirmShow: false,
      addConfirmShow: false,
      addAlertShow: false,
      errorMessage: "",
      msgtype: "",
      type : "",
      oldcode : this.props.oldcode,
      confirmMessage: "",
      documents: this.props.defaultprocessDocs,
      sameVehicles: this.props.samevehicleChecked,
    };
    this.onTagsChange = this.onTagsChange.bind(this);
  }

  setSelectedRouteCodes = (val) => {
    this.props.handleRouteCodeChange(val);
  };

  selectedRouteCodeArr = (val) => {
    this.props.RouteCodeArr(val);
  };

  setSelectedSites = (val) => {
    this.props.handleSiteChange(val);
  };

  selectedSitesArr = (val) => {
    this.props.sitesArr(val);
  };

  onTagsChange = (event, value) => {
    //this.props.handleSiteChange(value);
  };
  getRouteScheduler = (routesSchedule) => {
    this.props.getValuestoApp(routesSchedule);
  };

  onDateselection = (date) => {
    console.log("T11 inside dateselection", date);
    const Seldate = moment(date[0]).format("YYYY-MM-DD");
    console.log("T11 inside dateselection", Seldate);
    this.props.handleDateChange(Seldate);
  };

  // Auto

  autoGeneratedRouteClick = () => {
    this.props.autoGenerateTrips();
    this.setState({
      addConfirmShow: false,
      msgtype: "",
      type:"",
    });
  };

  OnSameVehcheckBoxChange = () => {
    console.log("T222 docpanel - to plan change");
    this.setState({ sameVehicles: !this.state.sameVehicles });
    this.props.OncheckedSameVehicles(!this.state.sameVehicles);
  };

  autoResetRoutes = () => {
    this.props.autoResetTrips();
  };

  OnGroupLockingTrips = () => {
    this.props.grouplockTrips();
  };

  onConfirmNo = () => {
    console.log("inside confirm No");
    this.setState({
      addConfirmShow: false,
      msgtype: "",
      type : "",
    });
  };

  onConfirmClick = (type) => {
     console.log("on cofirm click ", type)
    let tripsList = this.props.tripsPanel;

    var Validatecount = 0;
    var Lockcount = 0;
    var OptimisedTrips = 0;
    var DeletedCount = 0;
    var DocCount = 0;
    for (let jj = 0; jj < this.props.dropsPanel.drops.length; jj++) {
      let doc = this.props.dropsPanel.drops[jj];
      if (
        (doc.type === "open" || doc.type === "Allocated") &&
        (doc.dlvystatus === "0" || doc.dlvystatus === "8")
      ) {
        DocCount = DocCount + 1;
      }
    }

    for (let jk = 0; jk < this.props.dropsPanel.pickUps.length; jk++) {
      let doc = this.props.dropsPanel.pickUps[jk];
      if (
        doc.type === "open" &&
        (doc.dlvystatus === "0" || doc.dlvystatus === "8")
      ) {
        DocCount = DocCount + 1;
      }
    }

    for (let i = 0; i < tripsList.length; i++) {
      var trip = tripsList[i];
      if (trip.lock && !trip.tmsValidated) {
        Validatecount = Validatecount + 1;
      }
      if (!trip.lock && trip.optistatus === "Optimized") {
        Lockcount = Lockcount + 1;
      }
      if (!trip.lock && trip.optistatus === "Open") {
        OptimisedTrips = OptimisedTrips + 1;
      }
      if (
        !trip.lock &&
        (trip.optistatus === "Optimized" || trip.optistatus === "Open")
      ) {
        DeletedCount = DeletedCount + 1;
      }
    }

    console.log("T333 tripsList =", tripsList);

    let mess = "";
    if (type === "1") {
       console.log("1")
      if (DocCount > 0) {
        console.log("confirm 1")
//        mess = "Are you sure you want to confirm the auto-generation of the trips?";
//        this.setState({
//          addConfirmShow : true,
//          confirmMessage: mess,
//          msgtype: type,
//          type : "success"
//        });
        this.props.openPopupAuto(true);
      } else {
        this.setState({
          confirmMessage: "There are no documents available for trip creation.",
          addConfirmShow: true,
          type : "error",
          msgtype: type,
        });
      }
    } else if (type === "2") {
      if (Lockcount > 0) {
        mess = "Are you sure you want to lock the trip(s)?";
        this.setState({
          addConfirmShow: true,
          confirmMessage: mess,
          msgtype: type,
           type : "success"
        });
      } else {
        this.setState({
          confirmMessage : "There are no unlocked trips.",
          addConfirmShow: true,
          type : "error",
           msgtype: type
        });
      }
    } else if (type === "3") {
      if (Validatecount > 0) {
        mess = "Are you sure you want to validate the trip(s)?";
        this.setState({
          addConfirmShow : true,
          confirmMessage: mess,
          msgtype: type,
           type : "success"
        });
      } else {
        this.setState({
          confirmMessage: "There are no trips available to validate.",
          addConfirmShow: true,
           msgtype: type,
          type : "error",

        });
      }
    } else if (type === "4") {
      if (DeletedCount > 0) {
        mess = "Are you sure you want to delete all the unlocked trip(s)?";
        this.setState({
          addConfirmShow: true,
          confirmMessage: mess,
          msgtype: type,
           type : "success"
        });
      } else {
        this.setState({
              confirmMessage: "There are no trips available to delete.",
          addConfirmShow: true,
           msgtype: type,
          type : "error"
        });
      }
    } else if (type === "5") {
      if (OptimisedTrips > 0) {
        mess = "Are you sure you want to optimize the trip(s)?";
        this.setState({
          addConfirmShow: true,
          confirmMessage: mess,
          msgtype: type,
           type : "success"
        });
      } else {
        this.setState({
          confirmMessage: "There are no trips available to optimize.",
          addConfirmShow: true,
           msgtype: type,
          type : "error"
        });
      }
    }
     else if (type === "6") {
          if (Validatecount > 0) {
            mess = "Are you sure you want to unlock the trip(s)?";
            this.setState({
              addConfirmShow: true,
              confirmMessage: mess,
              msgtype: type,
               type : "success"
            });
          } else {
            this.setState({
              confirmMessage: "There are no locked trips.",
              addConfirmShow: true,
               msgtype: type,
              type : "error"
            });
          }
        }
  };

  onConfirmYes = (type) => {
    console.log("inside confirm YEs", type);
    if (type === "1") {
      // this.autoGeneratedRouteClick();
      this.props.openPopupAuto(true);
    } else if (type === "2") {
      this.OnGroupLockingTrips();
    } else if (type === "3") {
      this.OnGroupValidateTrips();
    } else if (type === "4") {
      this.autoResetRoutes();
    } else if (type === "5") {
      this.OnGroupOptimiseTrips();
    }
     else if (type === "6") {
              this.OnGroupUnlockTrips();
       }


    //   this.props.confirmTrip(this.state.currentTrip, 'Open');
    this.setState({
      addConfirmShow: false,
      confirmMessage : "",
      msgtype: "",
      type : "",
    });
  };

  OnGroupOptimiseTrips = () => {
    console.log("TOOO inside optmise trip");



   if(this.props.oldCode) {
      this.props.groupOptmiseTrips();
   }
   else {
      this.props.groupNextBillionsOptmiseTrips();
   }

  };


   OnGroupUnlockTrips = () => {
        console.log("TOOO inside optmise trip");
        this.props.groupunlockTrips();
      };

  OnGroupValidateTrips = () => {
    this.props.onValidateAll();
    /*
          this.setState({
              confirmMessage: this.props.t('AllValidate'),
              addvalidateconfirmShow: true,
          });
*/
  };
  onGroupValidateNo = () => {
    this.setState({
      addvalidateconfirmShow: false,
    });
  };

  onGroupValidateYes = () => {
    this.props.onValidateAll();
    console.log("GV - Yes confirm for group Valdiation");
    this.setState({
      addvalidateconfirmShow: false,
    });
  };

  // handleDocProcessChange = (event) => {
  //   console.log("Changed Value =", event.target.value);
  //   this.props.onDocProcessChange(event.target.value);
  //   this.setState({
  //     documents: event.target.value,
  //   });
  // };

  handleDocProcessChange = (event) => {
    const value = event.target.value;
    console.log("Changed Value =", value);

    // Allow only numeric values and restrict special characters
    if (/^\d*$/.test(value)) {
      // Check if the input contains only digits
      const numericValue = parseInt(value, 10);

      if (numericValue > 0) {
        // If value is greater than 0, update state and call the parent handler
        this.props.onDocProcessChange(numericValue);
        this.setState({
          documents: numericValue,
        });
      } else if (value === "") {
        // Allow clearing the input
        this.setState({
          documents: "",
        });
      }
    }
  };


  handleCodeChange = (e) => {
   console.log("T222 data update",e)
   console.log("T222 data update",!this.props.oldCode)
    this.props.handleCodeExecution(!this.props.oldCode);
  }

  render() {
    let optionItems = [];
    var optionSelected = {};
    var selectedSite = {};
    let addAlertClose = () => this.setState({ addConfirmShow: false });
    let optionRouteCodeItems = [];
    var optionSelectedRouteCode = {};
    var selectedRouteCode = {};
    var placeHolder = "All";
    this.props.sites &&
      this.props.sites.length > 0 &&
      this.props.sites.map((site) => {
        if (site.id == this.props.selectedSite) {
          selectedSite = site;
          placeHolder = site.value;
          optionSelected.value = site.id;
          optionSelected.label = site.value + "(" + site.id + ")";
        }
        optionItems.push({
          value: site.id,
          label: site.value + "(" + site.id + ")",
        });
      });
    this.props.routecodes &&
      this.props.routecodes.length > 0 &&
      this.props.routecodes.map((routecode) => {
        if (routecode.routeNo == this.props.selectedRouteCode) {
          selectedRouteCode = routecode;
          placeHolder = routecode.routeDesc;
          optionSelected.value = routecode.routeNo;
          optionSelected.label = routecode.routeDesc;
        }
        optionRouteCodeItems.push({
          value: routecode.routeNo,
          label: routecode.routeDesc,
        });
      });




    return (
      <>
        <Form className="row_nav" style={{ height: "100%" }}>
          <div style={{ display: this.props.vehicleShow }}>
            <FormGroup className="select2-container mb-0 col-md-2 col-lg-2 col-xl-2">
              <MultiSelect
                setSelectedSites={this.setSelectedSites}
                selectedSitesArr={this.selectedSitesArr}
                options={optionItems}
              />
            </FormGroup>
          </div>
          <div style={{ display: this.props.vehicleShow }}>
            <FormGroup className="Select2-date p-1 ml-1 col-md-2 col-lg-2 col-xl-2 mb-1">
              <span style={{color:"#505D69",fontWeight:"bold"}}>Date </span>

              <Flatpickr

                className="form-control"
                dateFormat="m/d/Y"
                style={{ width: "auto",fontWeight:"bold" }}
                value={this.props.selectedDate}
                onChange={this.onDateselection}
              />
            </FormGroup>
            &emsp;
          </div>

          <div style={{ display: this.props.vehicleShow }}>
            <FormGroup className="select2-container ml-3 mb-0 col-md-2 col-lg-2 col-xl-2">
              <MultiRouteCode
                setSelectedRouteCodes={this.setSelectedRouteCodes}
                selectedRouteCodeArr={this.selectedRouteCodeArr}
                options={optionRouteCodeItems}
              />
            </FormGroup>
          </div>

          <div
          //  className="SideNav_Btns"
            style={{
              alignSelf: "center",
             // display : 'flex',

              justifyContent: "space-between",
              display: this.props.vehicleShow,
            }}
          >
   <Toolbar  style={{gap : '16px'}}>
        <Tooltip
         title={
                <span style={{ fontSize: "1.25rem" /* 20px */ }}> Auto Generate Route </span> }
         >
           <IconButton style={{backgroundColor : "#4285F4"}}>
            <HdrAutoIcon style={{ fontSize: 28, color: 'white'}}  onClick={() => this.onConfirmClick("1")} />
          </IconButton>
        </Tooltip>

         <Tooltip title={
                                  <span style={{ fontSize: "1.25rem" /* 20px */ }}> Group Optimise </span> }
                           >
                  <IconButton style={{backgroundColor : "#6B7280"}}>
                    <RouteIcon style={{ fontSize: 28, color: 'white'}}  onClick={() => this.onConfirmClick("5")}/>
                  </IconButton>
                </Tooltip>

        <Tooltip title={
                                                   <span style={{ fontSize: "1.25rem" /* 20px */ }}> Group Lock </span> }
                                            >
           <IconButton style={{backgroundColor : "#34D399"}}>
            <LockIcon style={{ fontSize: 28, color: 'white' }}  onClick={() => this.onConfirmClick("2")} />
          </IconButton>
        </Tooltip>

        <Tooltip title={
                                                   <span style={{ fontSize: "1.25rem" /* 20px */ }}> Group Unlock </span> }
                                            >
           <IconButton style={{backgroundColor : "#8B5CF6"}}>
            <LockOpenIcon style={{ fontSize: 28, color: 'white' }}  onClick={() => this.onConfirmClick("6")} />
          </IconButton>
        </Tooltip>

       <Tooltip title={
                                                  <span style={{ fontSize: "1.25rem" /* 20px */ }}> Group Validate </span> }
                                           >
                 <IconButton style={{backgroundColor : "#F59E0B"}}>
                  <DoneAllIcon style={{ fontSize: 28, color: 'white' }}   onClick={() => this.onConfirmClick("3")}/>
                </IconButton>
              </Tooltip>

        <Tooltip title={
                                                   <span style={{ fontSize: "1.25rem" /* 20px */ }}> Group Delete Trips </span> }
                                            >
                  <IconButton style={{backgroundColor : "#EF4444    "}}>
                   <DeleteIcon style={{ fontSize: 28, color: 'white' }}  onClick={() => this.onConfirmClick("4")} />
                 </IconButton>
               </Tooltip>
             </Toolbar>

          </div>

           <div style={{ display: this.props.vehicleShow  }}>
                      <div
                        className="refreshbtn"
                        style={{ marginTop : "5px", paddingTop: "25px", paddingLeft: "25px" }}
                      >
                         <button
                                      type="button"
                                      class="btn btn-primary"
                                      onClick={() =>  this.props.refreshAllPanels()}
                                    >
                                      Refresh
                                    </button>
                      </div>

                    </div>
                     <div style={{ display: this.props.vehicleShow  }}>
                                          <div
                                            className="refreshbtn"
                                            style={{ marginTop : "5px", paddingTop: "25px", paddingLeft: "25px" }}
                                          >
                                            <Switch
                                                  checked={this.props.oldCode}
                                                  onChange={this.handleCodeChange}
                                                  inputProps={{ 'aria-label': 'controlled' }}
                                                />
                                          </div>

                                        </div>
          <div
            style={{
              display: this.props.vrShow,
              width: "60%",
              alignSelf: "center",
            }}
          >
            <ul className="list-unstyled CTAs" style={{ float: "center" }}>
              <li>
                <button
                  type="button"
                  class="btn btn-primary"
                  style={{ display: this.props.vrShow }}
                  onClick={() => this.props.onVRhide()}
                >
                  <span>{this.props.t("Back")}</span>
                </button>
              </li>
            </ul>
          </div>
        </Form>
        <AlertNew
          show={this.state.addConfirmShow}
          onClose={this.onConfirmNo}
          message={this.state.confirmMessage}
          onConfirm={this.onConfirmYes}
          msgtype={this.state.msgtype}
          type = {this.state.type}
        ></AlertNew>
      </>
    );
  }
}

export default withNamespaces()(SideNav);
